FROM  golang:1.8

COPY . /go/src/github.com/MickayG/moby-kafka-logdriver
RUN cd /go/src/github.com/MickayG/moby-kafka-logdriver && go get -t && go build --ldflags '-extldflags "-static"' -o /usr/bin/kafka-logdriver
